### ISSUE TITLE
Mapping parameters

### ISSUE THREAD

**Issue by motleydev** [beerkit/beer.db#2]
Hi, I'm trying to map the parameters of this command to the current status of the `beerdb` util

`beerdb setup --include ./at-austria --worldinclude ./world.db`

It seems setup is not a valid parameter anymore and --worldinclude is not a valid flag?

**Comment by geraldb** [comment]
@motleydev   Hello, thanks for your interest in beer.db.

You're right. The idea was to make it easier / simplify.  The recommend way is to use datafiles to setup new beer.db databases, e.g. Datafile

     world  'world.db'
     beer    'at-austria'

Than use:

   $ beerdb build 

The "workaround" for all command line is something like:

$ worlddb setup --include ./world.db
$ beerdb create
$ beerdb load --include ./at-austria

Cheers.  Sorry for the trouble currently trying to update / making the setup (and format) easier.
